"""Initial migration

Revision ID: 9e5b5b4d7461
Revises: 
Create Date: 2026-02-06 17:07:45.269780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e5b5b4d7461'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token'), 'api_tokens', ['token'], unique=True)
    op.create_table('operations_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operations_log_operation_type', 'operations_log', ['operation_type'], unique=False)
    op.create_index('idx_operations_log_started_at', 'operations_log', ['started_at'], unique=False)
    op.create_index('idx_operations_log_status', 'operations_log', ['status'], unique=False)
    op.create_table('processed_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inner_id', sa.String(), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_data_active_status', 'processed_data', ['active_status'], unique=False)
    op.create_index('idx_processed_data_inner_id', 'processed_data', ['inner_id'], unique=False)
    op.create_index(op.f('ix_processed_data_inner_id'), 'processed_data', ['inner_id'], unique=False)
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inner_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_loaded_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('active_status', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_data_active_status', 'raw_data', ['active_status'], unique=False)
    op.create_index('idx_raw_data_is_processed', 'raw_data', ['is_processed'], unique=False)
    op.create_index('idx_raw_data_last_updated_at', 'raw_data', ['last_updated_at'], unique=False)
    op.create_index('idx_raw_data_source', 'raw_data', ['source'], unique=False)
    op.create_index(op.f('ix_raw_data_inner_id'), 'raw_data', ['inner_id'], unique=True)
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_successful_date', sa.Date(), nullable=False),
    sa.Column('last_change_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_sync_state_single_record')
    )
    op.create_index(op.f('ix_sync_state_last_successful_date'), 'sync_state', ['last_successful_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_state_last_successful_date'), table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_raw_data_inner_id'), table_name='raw_data')
    op.drop_index('idx_raw_data_source', table_name='raw_data')
    op.drop_index('idx_raw_data_last_updated_at', table_name='raw_data')
    op.drop_index('idx_raw_data_is_processed', table_name='raw_data')
    op.drop_index('idx_raw_data_active_status', table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_processed_data_inner_id'), table_name='processed_data')
    op.drop_index('idx_processed_data_inner_id', table_name='processed_data')
    op.drop_index('idx_processed_data_active_status', table_name='processed_data')
    op.drop_table('processed_data')
    op.drop_index('idx_operations_log_status', table_name='operations_log')
    op.drop_index('idx_operations_log_started_at', table_name='operations_log')
    op.drop_index('idx_operations_log_operation_type', table_name='operations_log')
    op.drop_table('operations_log')
    op.drop_index(op.f('ix_api_tokens_token'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
